name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.100'
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh