name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Rubin.Static.sln

    - name: Build
      run: dotnet build Rubin.Static.sln --no-restore --configuration Release

    - name: Tests
      run: dotnet test tests/Rubin.Markdown.Tests/Rubin.Markdown.Tests.csproj --no-build --verbosity=normal

    - name: Test Rubin.Static.Tests
      run: dotnet test tests/Rubin.Static.Tests/Rubin.Static.Tests.csproj --no-build --verbosity=normal
